micronaut:
  application:
    name: demoExampleMicronautCrud
endpoints:
  env:
    sensitive: false
  health:
    details-visible: ANONYMOUS
datasources:
  default:
    url: jdbc:h2:mem:devDb;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
